name: "subscriptions"

volumes:
  pgdata:

services:
  db:
    image: postgres:17-alpine
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "db"
    volumes:
      - pgdata:/var/lib/postgresql/data
